import {StyleSheet} from 'react-native';
import LayoutStyle from './LayoutStyle';
import Colors from './Colors';
import {deviceHight, deviceWidth} from '../utils/DeviceInfo';
import FontFamily from '../assets/FontFamily';
import CommonStyles from './CommonStyles';

const MystaysStyle = StyleSheet.create({
  mainContainer: {},
  homeContainer: {
    backgroundColor: Colors.goastWhite,
  },
  headerContainerBlue: {
    ...CommonStyles.directionRowSB,
    backgroundColor: Colors.secondary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  profileImgContainer: {
    ...CommonStyles.directionRowCenter,
  },
  iconContainer: {...CommonStyles.directionRowCenter},
  smallRound: {
    borderRadius: 20,
    backgroundColor: Colors.red,
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: -22,
    padding: 3.5,
    ...LayoutStyle.marginBottom20,
    ...LayoutStyle.marginLeft10,
  },
  formContainer: {
    height: deviceHight,
    width: deviceWidth,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.paleBlue,
    paddingHorizontal: 0,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    paddingVertical: 12,
  },
  activeTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: Colors.secondary,
    paddingVertical: 12,
  },
  tabText: {
    color: Colors.tabText,
    fontSize: 14,
    fontFamily: FontFamily.RobotoRegular,
  },
  tabActiveText: {
    color: Colors.secondary,
    fontSize: 14,
    fontFamily: FontFamily.RobotoMedium,
  },
  tabListcontainer: {
    flex: 1,
    backgroundColor: Colors.goastWhite,
  },
  scrollContent: {
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 50,
    minHeight: 200,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 50,
  },
  emptyText: {
    color: Colors.grayText,
    ...LayoutStyle.fontSize14,
    fontFamily: FontFamily.RobotoRegular,
  },
  staysListContainer: {
    flexDirection: 'row',
    padding: 12,
    marginTop: 15,
    marginBottom: 10,
    elevation: 4,
    backgroundColor: Colors.white,
    borderRadius: 10,
    borderWidth: 0.2,
    borderColor: Colors.grayBorder,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    position: 'relative',
    overflow: 'visible',
    minHeight: 120,
  },
  presentLabel: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: Colors.green,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    zIndex: 10,
  },
  presentLabelText: {
    color: Colors.white,
    fontSize: 10,
    fontFamily: FontFamily.RobotoMedium,
  },
  staysImg: {
    height: 120,
    width: 100,
    borderRadius: 8,
    resizeMode: 'cover',
    backgroundColor: Colors.lightGray,
  },
  staysContentContainer: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'flex-start',
  },
  staysHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  staysText: {
    color: Colors.black,
    fontSize: 16,
    fontFamily: FontFamily.RobotoMedium,
    flex: 1,
    marginRight: 8,
  },
  shareButton: {
    padding: 4,
  },
  staysAddress: {
    color: Colors.black,
    fontSize: 11,
    marginLeft: 6,
    fontFamily: FontFamily.RobotoRegular,
    flex: 1,
    flexWrap: 'wrap',
  },
  checkDate: {
    color: Colors.black,
    fontSize: 11,
    fontFamily: FontFamily.RobotoBold,
    marginVertical: 3,
  },
  checkDateAns: {
    color: Colors.black,
    fontSize: 11,
    fontFamily: FontFamily.RobotoRegular,
    marginLeft: 4,
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginVertical: 2,
  },
  detailsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 2,
  },
  iconAddress: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: 6,
  },
  timeSheetText: {
    color: Colors.black,
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoMedium,
  },
  timesheetAddress: {
    color: Colors.black,
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    ...LayoutStyle.marginLeft10,
    ...LayoutStyle.marginVertical5,
  },
  calenderContainer: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    ...LayoutStyle.margin15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    ...LayoutStyle.paddingBottom10,
    borderWidth: 0.1,
    borderColor: Colors.gray,
  },
  calenderTextDate: {
    borderBottomWidth: 2,
    ...LayoutStyle.fontSize30,
    fontFamily: FontFamily.RobotoMedium,
    color: Colors.black,
    ...LayoutStyle.paddingBottom10,

    borderColor: Colors.gray,
  },
  calenderButton: {
    alignSelf: 'center',
    marginTop: '20%',
  },
  btnStyle: {
    backgroundColor: Colors.goastWhite,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.secondary,
    ...LayoutStyle.padding15,
  },
  checkDateText: {
    color: Colors.grayText,
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    ...LayoutStyle.marginVertical10,
  },
  checkDateTextBlack: {
    color: Colors.blackText,
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    ...LayoutStyle.marginVertical10,
  },
  checkDateValue: {
    color: Colors.black,
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    width: deviceWidth / 2,
  },
  detailsRoom: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.paleBlue,
    borderRadius: 20,
    marginRight: 10,
    marginTop: 8,
    marginBottom: 0,
    alignSelf: 'flex-start',
  },
  detailsView: {
    flexDirection: 'row',
  },
  detailsViewMystay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailsText: {
    color: Colors.blue,
    ...LayoutStyle.fontSize10,
    fontFamily: FontFamily.RobotoRegular,
    textAlign: 'center',
  },
  addressText: {
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.blackText,
    width: deviceWidth / 1.5,
    ...LayoutStyle.marginLeft20,
  },
  btnFood: {
    ...CommonStyles.directionRowSB,
    borderWidth: 1,
    ...LayoutStyle.padding10,
    ...LayoutStyle.marginTop20,
    borderRadius: 10,
    borderColor: Colors.secondary,
  },
  foodText: {
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.secondary,
  },
  btnRoomContainer: {
    ...CommonStyles.directionRowSB,
    flexGrow: 1,
    ...LayoutStyle.marginTop20,
  },
  RadiusBtnStyle: {
    borderRadius: 10,
  },
  RadiusRoomBtnStyle: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.secondary,
    borderRadius: 10,
  },
  imgFood: {
    height: deviceHight / 3.5,
    width: deviceWidth - 10,
    alignItems: 'center',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  itemContainerFood: {
    ...LayoutStyle.marginBottom30,
  },
  mealTitle: {
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.blackText,
  },
  mealText: {
    ...LayoutStyle.fontSize10,
    fontFamily: FontFamily.RobotoMedium,
    color: Colors.grayText,
    ...LayoutStyle.marginTop10,
  },
  foodListContainer: {
    ...LayoutStyle.padding15,
  },
  header: {
    ...LayoutStyle.fontSize12,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.blackText,
    ...LayoutStyle.marginBottom10,
  },
  listContent: {
    ...LayoutStyle.paddingBottom15,
  },
  pageHeader: {
    ...LayoutStyle.fontSize14,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.whiteText,
    ...LayoutStyle.marginLeft10,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: FontFamily.RobotoMedium,
    color: Colors.white,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  container: {
    backgroundColor: Colors.goastWhite,
  },
  textarea: {
    height: 100,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    textAlignVertical: 'top',
    ...LayoutStyle.marginTop20,
    ...LayoutStyle.paddingHorizontal10,
    fontFamily: FontFamily.RobotoRegular,
    ...LayoutStyle.fontSize14,
    color: Colors.blackText,
  },
  roomBox: {
    maxWidth: 100,
    borderRadius: 12,

    alignItems: 'center',
    position: 'relative',
    ...LayoutStyle.marginBottom10,
  },
  roomText: {
    ...LayoutStyle.fontSize10,
    fontFamily: FontFamily.RobotoMedium,
    color: Colors.blackText,
  },
  greenStripContainer: {
    position: 'absolute',
    right: 4,
    top: '25%',
    bottom: '25%',
    width: 6,
    backgroundColor: 'transparent',

    alignItems: 'center',
  },
  greenStrip: {
    width: 4,
    height: '100%',
    backgroundColor: Colors.selectedGreen,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  available: {
    backgroundColor: Colors.lightGray,
  },
  grayStrip: {
    width: 4,
    height: '100%',
    backgroundColor: Colors.lightGray,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  legendRow: {
    ...CommonStyles.directionRowCenter,
    ...LayoutStyle.marginVertical30,
  },
  legendBox: {
    width: 16,
    height: 16,
    marginRight: 4,
  },
  legendLabel: {
    ...LayoutStyle.fontSize10,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.blackText,
  },
  btnStylesmall: {
    ...LayoutStyle.marginHorizontal30,
    borderRadius: 10,
  },
  successScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    // paddingTop: deviceHight / 6,
  },
  successContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  thumbUpIconContainer: {
    marginBottom: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbUpImg: {
    height: deviceHight / 3,
    width: deviceWidth - 100,
    // marginTop: deviceWidth / 3,
  },
  updateText: {
    ...LayoutStyle.fontSize14,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.black,
    ...LayoutStyle.marginTop20,
    width: deviceWidth - 50,
    textAlign: 'center',
    lineHeight: 22,
  },
  requestIdText: {
    ...LayoutStyle.fontSize14,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.black,
    ...LayoutStyle.marginTop15,
    textAlign: 'center',
  },
  viewStatusText: {
    ...LayoutStyle.fontSize14,
    fontFamily: FontFamily.RobotoRegular,
    color: Colors.secondary,
    ...LayoutStyle.marginRight8,
  },
  btnStatus: {
    ...CommonStyles.directionRowCenter,
    alignSelf: 'center',
    ...LayoutStyle.paddingBottom30,
    paddingTop: 20,
  },
  statusContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 0,
    position: 'relative',
  },
  iconColumn: {
    alignItems: 'center',
    width: 30,
    marginRight: 15,
  },
  circle: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  verticalLine: {
    width: 1,
    height: 50,
    backgroundColor: 'transparent',
    marginTop: 4,
    marginBottom: 4,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#999',
  },
  textColumn: {
    flex: 1,
    paddingLeft: 0,
    paddingTop: 0,
  },
  label: {
    fontSize: 16,
    color: '#666',
    fontFamily: FontFamily.RobotoRegular,
    marginTop: 0,
  },
  labelBold: {
    fontSize: 16,
    fontFamily: FontFamily.RobotoMedium,
    color: '#333',
    marginTop: 0,
  },
  timestamp: {
    fontSize: 14,
    color: '#888',
    fontFamily: FontFamily.RobotoRegular,
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    position: 'relative',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.modalTransparent,
  },
  modalContainer: {
    flex: 1,
    width: deviceWidth,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  modalWrapper: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingTop: 40,
    paddingBottom: 40,
  },
  modalScrollView: {
    flex: 1,
    width: '100%',
  },
  modalContentContainer: {
    paddingBottom: 30,
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingTop: 10,
  },
  modalCardContainer: {
    overflow: 'hidden',
    width: '100%',
    marginBottom: 0,
  },
  modalImage: {
    width: '100%',
    height: 220,
    resizeMode: 'cover',
    backgroundColor: Colors.lightGray,
  },
  modalContent: {
    width: '100%',
    paddingVertical: 10,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalTitle: {
    color: Colors.black,
    fontSize: 18,
    fontFamily: FontFamily.RobotoMedium,
    flex: 1,
    marginRight: 10,
  },
  modalDateRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: 6,
  },
  modalRoomDetails: {
    marginTop: 6,
    marginBottom: 0,
    flexDirection: "row"
  },
  modalRoomBadges: {
    marginTop: 8,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  referButtonContainer: {
    width: '100%',
    marginTop: 25,
    paddingHorizontal: 0,
    alignItems: 'center',
  },
  referButton: {
    width: '100%',
    backgroundColor: Colors.secondary,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: 4,
  },
});

export default MystaysStyle;
